#! /bin/sh

PROCESS_ID=$(ps x | grep 'node dist/server/entry.mjs' | grep -v grep | awk '{print $1}')
if [ -z "$PROCESS_ID" ];
then
    nohup node dist/server/entry.mjs > log/$(date +"%Y-%m-%d_%H-%M-%S").log 2>&1 &
else
    echo "node is already running"
fi
