#! /bin/sh

PROCESS_ID=$(ps x | grep 'node dist/server/entry.mjs' | grep -v grep | awk '{print $1}')
if [ ! -z "$PROCESS_ID" ];
then
    pkill -9 -f "node dist/server/entry.mjs"
else
    echo "node is not running"
fi
